# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_snippets_v1.BaseModel')),
                ('title', models.CharField(default='Untitled Snippet', max_length=255)),
                ('url', models.URLField()),
                ('color', models.CharField(choices=[('white', 'white'), ('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('yellow', 'yellow'), ('orange', 'orange'), ('teal', 'teal'), ('gray', 'gray')], default='white', max_length=20)),
                ('starred', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
            bases=('api_snippets_v1.basemodel',),
        ),
    ]
