# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets_v1', '0003_snippet_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snippet',
            unique_together=set([('title', 'url')]),
        ),
    ]
