# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets_v1', '0004_auto_20161024_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
