# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-04 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets_v1', '0008_auto_20170131_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagsnippetrelation',
            unique_together=set([('owner', '_tag', '_snippet')]),
        ),
    ]
