# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_snippets_v1', '0009_auto_20170204_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category_name_blue',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_name_gray',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_name_green',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_name_orange',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_name_red',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_name_teal',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_name_white',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_name_yellow',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='tagsnippetrelation',
            unique_together=set([]),
        ),
    ]
